version: "3.8"
services:
  front:
    build:
      context: .
      dockerfile: local.Dockerfile
    volumes:
      - ./front:/front
    working_dir: /front
    ports:
      - 3011:3000
    tty: true
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "npm start"